### ISSUE TITLE
Improvement on README.md

### ISSUE THREAD

**Issue by vsupacha** [phondanai/flask-carpark#16]
Please consider the following improvement for your README.md.

- Use upto three-level of header (#, ##, ###). For example, use ## Preparation with ### Required libraries, ### Installation and ### Configuration
- Contents of README.md should contain (1) Requirements (2) Preparation (3) Concepts (4) Test
- Each <test case> should be marked as ### header, then each detail should be marked by bullet. For example, test case "Dashboard page" should be written as follows.

```
### Test case: Dashboard page
**Description**
Dashboard is page for display occupancy map. It shows status of slot that available or occupied.
 
**Procedure**
1. To send request from dashboard page to server for download the data
2. To display data on dashboard page

**Test data**
To send request to server

**Expected results**
To display occupancy map that available and occupied
```

**Comment by lin-nlh** [comment]
updated
